// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tskrazzjaaideabmitai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRza3JhenpqYWFpZGVhYm1pdGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTE3NDYsImV4cCI6MjA2NTQ4Nzc0Nn0.e6-5KJIrVhrfoNNW5P1MRZ6ko4NKvAOl_8x4FfX5LhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);